# Generated by Django 5.2 on 2025-04-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='encrypted_email',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='encrypted_username',
        ),
        migrations.AddField(
            model_name='credential',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
